import Head from 'next/head'
import { Container } from 'react-bootstrap'
// import React from 'react'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1 className="text-center">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </Container>
      </main>
    </>
  )
}
